[package]
name = "rgit"
version = "0.1.0"
authors = ["Yusei Ito <yuseikun@Outlook.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
sha1 = "0.6.0"